name: Python Version

on:
  workflow_call:
    inputs:
      python_version_file:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  python_versioon:
    name: Python Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.python_version.outputs.version }}
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout python version file
        uses: Bhacaz/checkout-files@v2
        with:
          files: ${{ inputs.python_version_file }}

      - name: Debug Step 1
        id: ls
        run: echo ::set-output name=templs::$(echo $(ls))

      - name: Debug Step 2
        run: echo ::debug::${{ steps.ls.outputs.templs }}

      - name: Python Version
        id: python_version
        run: echo ::set-output name=version::$(cat ${{ inputs.python_version_file }})

      