name: Python Version

on:
  workflow_call:
    inputs:
      python_version_file:
        required: true
        type: string

jobs:
  python_versioon:
    name: Python Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.python_version.outputs.version }}
    steps:
      - name: Checkout python version file
        uses: Bhacaz/checkout-files@v2
        with:
          files: ${{ inputs.python_version_file }}

      - name: Python Version
        id: python_version
        run: echo ::set-output name=version::$(cat ${{ inputs.python_version_file }})
