name: Python Version

on:
  workflow_call:
    inputs:
      python_version_file:
        required: true
        type: string

jobs:
  get_python_version:
    name: Get Python Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.echo_version.outputs.version }}
    steps:
      - name: Debug Step 1
        id: ls
        run: echo ::set-output name=templs::$(ls)


      - name: Debug Step 2
        run: echo ::debug::${{ steps.ls.outputs.templs }}

      - name: Echo Version
        id: echo_version
        run: echo ::set-output name=version::$(cat ${{ inputs.python_version_file }})
