name: Setup Repository and Python

on:
  workflow_call:
    inputs:
      python_version_file:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  setup_repository:
    name: Setup Repository
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.python_version.outputs.version }}
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Step 1
        id: ls
        run: echo ::set-output name=templs::$(echo $(ls))

      - name: Debug Step 2
        run: echo ::debug::${{ steps.ls.outputs.templs }}

      - name: Python Version
        id: python_version
        run: echo ::set-output name=version::$(cat ${{ inputs.python_version_file }})

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python_version.outputs.version }}